const express = require('express')
const exphbs = require('express-handlebars')
const app = express()
const produtosRoutes = require('./routes/produtosRoutes')
const homeRoutes = require('./routes/homeRoutes')

//app.engine('handlebars', exphbs())
app.engine('handlebars', exphbs.engine())
app.set('view engine', 'handlebars')
app.use(  express.urlencoded({ extended: true }),)
app.use(express.json())
app.use(express.static('public'))
app.use('/', homeRoutes)
app.use('/produtos', produtosRoutes)
app.listen(3000)